FROM gcr.io/deeplearning-platform-release/base-cpu:latest

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt \
    --index-url "https://artifactory.ida.avast.com/artifactory/api/pypi/pypi-remote/simple/" \
    --extra-index-url "https://artifactory.ida.avast.com/artifactory/api/pypi/pypi-local/simple/" --no-warn-script-location \
