wanna_project:
  name: kubeflow-bigquery
  version: 0.0.0
  authors: ["john.doe@example.com", "jane.doe@example.com"]

gcp_profiles:
  - profile_name: default
    project_id: "your-gcp-project-id"
    zone: europe-west1-b
    bucket: "your-staging-bucket-name"
    labels:
    service_account:
    network: default

docker:
  images: []
  repository: wanna-samples
  cloud_build: true

pipelines:
  - name: kubeflow-bigquery-pipeline
    schedule:
      cron: 2 * * * *
    bucket: "your-staging-bucket-name"
    pipeline_file: pipeline/pipeline.py
    pipeline_params: pipeline/params.yaml
    docker_image_ref: []
