FROM docker.ida.avast.com/dockerhub/python:3.8-slim-buster

ARG INDEX_URL=https://artifactory.ida.avast.com/artifactory/api/pypi/pypi-remote/simple
ARG EXTRA_INDEX_URL=https://artifactory.ida.avast.com/artifactory/api/pypi/pypi-local/simple

RUN mkdir -p $HOME/.pip
RUN printf "[global]\nindex-url=$INDEX_URL\nextra-index-url=$EXTRA_INDEX_URL" > $HOME/.pip/pip.conf

RUN mkdir /wanna

WORKDIR /wanna

ADD . .

RUN pip install poetry \
      && poetry install
