site_name: WANNA ML
repo_url: https://github.com/avast/wanna-ml/
repo_name: avast/wanna-ml
edit_uri: edit/master/docs/
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
        primary: indigo
        accent: indigo
        features:
          - navigation.instant
          - navigation.tracking
          - navigation.tabs
          - navigation.tabs.sticky
#          - navigation.sections
          - navigation.expand
          - navigation.indexes
          - navigation.top
          - toc.follow
          - toc.integrate
        highlightjs: true
        hljs_languages:
          - yaml
          - python
          - bash
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: indigo
      accent: indigo
      features:
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections
        - navigation.expand
        - navigation.indexes
        - navigation.top
        - toc.follow
        - toc.integrate
      highlightjs: true
      hljs_languages:
          - yaml
          - python
          - bash

nav:
    - Overview: 'index.md'
    - Installation: 'installation.md'
    - Tutorial:
        - 'Get Started': 'tutorial/index.md'
        - 'WANNA Project': 'tutorial/project.md'
        - 'WANNA Profile': 'tutorial/profile.md'
        - 'WANNA Docker': 'tutorial/docker.md'
        - 'WANNA Tensorboard': 'tutorial/tensorboard.md'
        - 'WANNA Notebook': 'tutorial/notebook.md'
        - 'WANNA Managed Notebook': 'tutorial/managed-notebook.md'
        - 'WANNA Job': 'tutorial/job.md'
        - 'WANNA Pipeline': 'tutorial/pipeline.md'
    - Plugins: 'cli/commands.md'

plugins:
- search
- mkdocstrings

markdown_extensions:
    - mkdocs-typer
    - mkdocs-click
    - toc:
        permalink: "#"
