FROM europe-docker.pkg.dev/vertex-ai/prediction/xgboost-cpu.1-4:latest

WORKDIR /wanna

ADD . /wanna/trainer

RUN pip install pandas sklearn xgboost && \
    pip install /wanna/trainer &&

ENV PYTHONPATH=/wanna/trainer

#CMD ["python", "-m", "wanna.train"]
