wanna_project:
  name: pipeline-sklearn-example-1
  version: 1
  authors: ["jane.doe@example.com"]

gcp_profiles:
  - profile_name: default
    project_id: your-gcp-project-id
    zone: europe-west1-b
    region: europe-west1
    bucket: your-staging-bucket-name
    labels:
    network: projects/your-gcp-project-id/global/networks/default
    service_account: wanna-dev@your-gcp-project-id.iam.gserviceaccount.com
    kms_key: "projects/project_id/locations/region/keyRings/key_ring/cryptoKeys/key"

#tensorboards:
#  - name: wanna-sample-pipeline-board

notification_channels:
  - type: pubsub
    name: wanna-sample-pipeline-pubsub-channel
    topics:
      - wanna-sample-pipeline-pubsub-channel

docker:
  images:
    - build_type: local_build_image
      name: train
      context_dir: .
      dockerfile: Dockerfile.train

    - build_type: provided_image
      name: serve
      image_url: europe-docker.pkg.dev/vertex-ai/prediction/xgboost-cpu.1-4:latest
  repository: wanna-samples

notebooks:
  - name: wanna-sklearn-sample-notebook
    service_account: wanna-dev@your-gcp-project-id.iam.gserviceaccount.com
    machine_type: n1-standard-4
    labels:
      notebook_usecase: wanna-notebook-sklearn-sample
    environment:
      docker_image_ref: train
    boot_disk:
      disk_type: pd_standard
      size_gb: 100
    data_disk:
      disk_type: pd_standard
      size_gb: 100
    bucket_mounts:
      - bucket_name: your-staging-bucket-name
    tensorboard_ref: wanna-sample-pipeline-board

pipelines:
  - name: wanna-sklearn-sample
    schedule:
      - environment: prod
        cron: 2 * * * *
      - environment: local
        cron: 4 * * * *
    bucket: gs://your-staging-bucket-name
    pipeline_function: "wanna_simple.pipeline.wanna_sklearn_sample"
    pipeline_params: params.yaml
    docker_image_ref: ["train", "serve"]
    tensorboard_ref: wanna-sample-pipeline-board
    enable_caching: false
    experiment: "wanna-sample-experiment"
    notification_channels_ref:
      - wanna-sample-pipeline-pubsub-channel
  - name: wanna-sklearn-sample-eval
    bucket: gs://your-staging-bucket-name
    pipeline_function: "wanna_simple.pipeline.wanna_sklearn_sample_eval"
    pipeline_params: params.eval.yaml
    docker_image_ref: ["train"]
    enable_caching: false
    experiment: "wanna-sample-experiment"
