wanna_project:
  name: pipeline-sklearn-example-1
  version: 1
  authors: ["jane.doe@example.com"]

gcp_profiles:
  - profile_name: default
    project_id: your-gcp-project-id
    zone: europe-west1-b
    region: europe-west1
    bucket: your-staging-bucket-name
    labels:
    network: projects/your-gcp-project-id/global/networks/default
    service_account: wanna-dev@your-gcp-project-id.iam.gserviceaccount.com

tensorboards:
  - name: wanna-sample-pipeline-board

docker:
  images:
    - build_type: local_build_image
      name: train
      context_dir: .
      dockerfile: Dockerfile.train

    - build_type: provided_image
      name: serve
      image_url: europe-docker.pkg.dev/vertex-ai/prediction/xgboost-cpu.1-4:latest
  repository: wanna-samples

notebooks:
  - name: wanna-sklearn-sample-notebook
    service_account: wanna-dev@your-gcp-project-id.iam.gserviceaccount.com
    machine_type: n1-standard-4
    labels:
      notebook_usecase: wanna-notebook-sklearn-sample
    environment:
      docker_image_ref: train
    boot_disk:
      disk_type: pd_standard
      size_gb: 100
    data_disk:
      disk_type: pd_standard
      size_gb: 100
    bucket_mounts:
      - bucket_name: your-staging-bucket-name
        bucket_dir: data
        local_path: /home/jupyter/mounted/gcs
    tensorboard_ref: wanna-sample-pipeline-board

pipelines:
  - name: wanna-sklearn-sample
    schedule:
      cron: 2 * * * *
    bucket: gs://your-staging-bucket-name
    pipeline_file: pipeline.py
    pipeline_params: params.yaml
    docker_image_ref: ["train", "serve"]
    tensorboard_ref: wanna-sample-pipeline-board
