FROM gcr.io/deeplearning-platform-release/base-cpu:latest

RUN sudo apt-get update -y && sudo apt-get install -y julia

# julia -e 'using Pkg; Pkg.add("IJulia");' # This fails on mac M1, so we run it directly in cloud

# deeplearning images automatically run /init.sh at the startup if this file exists
COPY init.sh /init.sh
RUN chmod +x /init.sh


