files: \.py
repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort
        language: python
        args: [
          "--line-length=120",
          "--py", "38",
          "--profile", "black",
        ]
        verbose: false
      - id: black
        name: black
        entry: poetry run black
        args: [
          "--line-length=120",
          "--target-version", "py38"
        ]
        language: python
        verbose: false
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: python
        args: [
          "--max-line-length=120",
          "--extend-ignore=E203,E712,E722,W503,W605"
        ]
        # E203 - Whitespace before ':'
        # E712 - Comparison to true should be 'if cond is true:' or 'if cond:'
        # E722 - Do not use bare except, specify exception instead
        # W503 - Line break occurred before a binary operator
        # W605 - Invalid escape sequence 'x'
        verbose: false
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: python
        args: [
          "--enable-all-extensions",
          "--errors-only",
          "--max-line-length=120",
          "--generated-members=torch.*",
          "--ignored-modules=multiprocess",
          "--disable=C0103,C0114,C0115,C0116,E1101"
        ]
        # C0103 - invalid-name
        # C0114 - missing-module-docstring
        # C0115 - missing-class-docstring
        # C0116 - missing-function-docstring
        verbose: false
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: python
        args: [
          "--ignore-missing-imports"
        ]
        verbose: false
      - id: pytest
        name: pytest
        entry: poetry run pytest
        language: python
        args: ["-W", "ignore", "-s"]
        always_run: true
        pass_filenames: false
        verbose: true

  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v2.3.0
  #   hooks:
  #     - id: check-yaml
  #       args: [--allow-multiple-documents]
  #     - id: trailing-whitespace
  #     - id: end-of-file-fixer
  #     - id: check-added-large-files