site_name: {{ cookiecutter.project_name }}
repo_url: https://github.com/user/{{ cookiecutter.project_repo_name }}
repo_name: {{ cookiecutter.project_repo_name }}
edit_uri: edit/master/docs/
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
        #    primary: indigo
        #    accent: indigo
        features:
          - navigation.instant
          - navigation.tracking
          - navigation.tabs
          - navigation.tabs.sticky
          - navigation.sections
          - navigation.expand
          - navigation.indexes
          - navigation.top
          - toc.follow
          - toc.integrate
        highlightjs: true
        hljs_languages:
          - yaml
          - python
          - bash
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  #    primary: indigo
  #    accent: indigo
      features:
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections
        - navigation.expand
        - navigation.indexes
        - navigation.top
        - toc.follow
        - toc.integrate
      highlightjs: true
      hljs_languages:
          - yaml
          - python
          - bash

nav:
    - Overview: 'index.md'

plugins:
- search
- mkdocstrings

markdown_extensions:
    - mkdocs-typer
    - mkdocs-click
    - toc:
        permalink: "#"
