wanna_project:
  name: {{ cookiecutter.project_slug|replace('_', '-') }}
  version: {{ cookiecutter.project_version }}
  authors: [{{ cookiecutter.project_owner_email }}]

gcp_profiles:
  - profile_name: default
    project_id: {{ cookiecutter.gcp_project_id }}
    zone: europe-west1-b
    bucket: {{ cookiecutter.gcp_bucket }}
    labels:
    service_account: {{ cookiecutter.gcp_service_account }}

tensorboards:
  - name: {{ cookiecutter.project_slug|replace('_', '-') }}-board

docker:
  images: []
  repository: {{ cookiecutter.gcp_artifact_registry_repository }}

pipelines:
  - name: {{ cookiecutter.project_slug|replace('_', '-') }}-pipeline
    schedule:
      cron: 2 * * * *
    bucket: gs://{{ cookiecutter.gcp_bucket }}
    pipeline_file: pipeline/pipeline.py
    pipeline_params: pipeline/params.yaml
    docker_image_ref: []
    tensorboard_ref: {{ cookiecutter.project_slug|replace('_', '-') }}-board
