  name: Slack Notification
  on:
    pull_request:
    push:
      branches: master
  jobs:
    test:
      name: test
      uses: tokorom/action-slack-incoming-webhook@main
  env:
    INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
 
