  name: Slack Notification
  on:
    pull_request:
    push:
      branches: master
  jobs:
    test:
      name: test
      runs-on: ubuntu-latest
      steps:
      - uses: tokorom/action-slack-incoming-webhook@main
      - name: test
  env:
    INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
 
