name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Extract Git Tag
        run: echo "GIT_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Build and publish to PYPI
        run: |
          poetry version ${{ env.GIT_TAG }}
          poetry build
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish
      - name: Publish docs
        run: |
          poetry install
          poetry run poe docs-deploy
