name: ReleaseNotice
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # To check the github context
      - name: Dump Github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
        # https://docs.slack.dev/tools/slack-github-action/sending-techniques/sending-data-webhook-slack-workflow/
      - name: Slack Notification on SUCCESS
        if: success()
        uses: slackapi/slack-github-action@v2.1.1
        with:
          payload-delimiter: "_"
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            release_name: "${{ github.event.release.name }}"
            release_tag: "${{ github.event.release.tag_name }}"
            author: "${{ github.actor }}"
            repository: "${{ github.repository }}"
            repo_name: "${{ github.event.repository.name }}"
            release_body: ${{ toJSON(github.event.release.body) }}
            release_url: "${{ github.event.release.html_url }}"
            published_at: "${{ github.event.release.published_at }}"
            is_prerelease: "${{ github.event.release.prerelease }}"
