name: ReleaseNotice
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # To check the github context
      - name: Dump Github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
        # https://docs.slack.dev/tools/slack-github-action/sending-techniques/sending-data-webhook-slack-workflow/
      - name: Slack Notification on SUCCESS
        if: success()
        uses: slackapi/slack-github-action@v2.1.1
        with:
          payload-delimiter: "_"
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            text: "A release is published."
            blocks:
              - type: header
                text:
                  type: plain_text
                  text: "wanna-ml ${{ github.event.release.name }} is published!"
              - type: section
                text:
                  type: mrkdwn
                  text: "*Author:*\n${{ github.actor }}"
              - type: section
                text:
                  type: mrkdwn
                  text: "*Information:*"
              - type: section
                text:
                  type: mrkdwn
                  text: ${{ toJSON(github.event.release.body) }}
              - type: section
                text:
                  type: mrkdwn
                  text: "${{ github.event.release.html_url }}"
