  name: Slack Notification
  on:
   release:
    types: [published]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Slack Notification on SUCCESS
          if: success()
          uses: tokorom/action-slack-incoming-webhook@main
          env:
            INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          with:
             text: Hello, Slack!
